### ISSUE TITLE
dpkg rule does not create output reproducibly

### ISSUE THREAD

**Issue by MarkusTeufelberger** [GoogleCloudPlatform/distroless#68]
If I run the exact same rule today and in three weeks, I might get a completely different version of the specified package.

Please add a hash to the rule, so it is possible to pin down exact versions.

Also it would be nice to be able to specify several package sources, since not all mirrors might keep older versions of packages around.

**Comment by MarkusTeufelberger** [comment]
#71 does fix the dpkg_src rule, not the dpkg rule itself.

I want control over which package gets installed, not only which global state of all possible package versions.
If the dpkg_src defines libfoo 0.1.2, but I want libfoo 0.1.3, I have to change to a more recent snapshot in dpkg_src and I risk that all my other dependencies suddenly change as well.

**Comment by r2d4** [comment]
I'm going to close this - the new `dpkg_src` rule takes a sha256 argument.  The source contains checksums for each package, which are checked upon downloading in `dpkg_list`.

As for package versioning - 
A `dpkg_list` rule can take multiple sources and will check each one in order.  If you need more granularity, you can use multiple `dpkg_src` and `dpkg_list` rules.

In the future, I think it would probably be good to include a "versioned" syntax to the `dpkg_list` rule, so that you could easily specify versions with something like `openssl=1.0.0`
