### ISSUE TITLE
How to deal with pip installs

### ISSUE THREAD

**Issue by sebgoa** [GoogleCloudPlatform/distroless#69]
A lot of current Python based containerized apps make use of `pip` to install module dependencies.

The Python example makes use of https://github.com/google/subpar and I guess we could also use grumpy to get a binary. This works in relatively simple cases but becomes quite complex when we need thirdparty modules.

A practical distroless python example would show how to deal with `pip install foo`

**Comment by mattmoor** [comment]
@steren @duggelz FYI

*(Sorry, this got long, and involves a lot of thinking out loud.  Hopefully it makes some sense, otherwise I'm happy to elaborate over VC tomorrow)*

Completely agree, the way I've been rationalizing this is:
 - Bazel needs support for pip
 - subpar should be able to bundle things appropriately into a PAR
 - distroless should be a suitable base for the PAR, with docker_build combining them.

So while I 100% agree that lack of `pip install` weakens the distroless (and `docker_build`) story; more broadly it is a huge hole in Bazel's story for Python dependencies.  This may come off as me saying "not our problem", but I think it is.  However, my (somewhat idealistic) hope thus far has been that we can avoid a distroless-/rules_docker-specific solution.

[Here](https://github.com/google/containerregistry/blob/master/WORKSPACE#L34) is a simple trick I've used to pull down a relatively simple PyPi package with Bazel (this obviously doesn't generalize).

---
@dlorenc and I have been experimenting with `npm install` a bit lately, which has a number of similarities to `pip`.  While it somewhat goes against what I was just saying about having a common solution, I do like the idea of a `foo_image` [rule](https://github.com/mattmoor/rules_nodejs/blob/master/WORKSPACE#L23-L26):
```python
node_image(
  name = "my_base",
  package_json = "//:package.json",
)
```
The idea above is that it would augment the distroless base runtimes with the desired `node_modules`.  This prototype works for some simple examples / demos, but the monolithic `node_modules` layer is undesireable for a number of reasons (mostly derived from its coarseness):
 - coarse incrementality (touching package.json would result in all packages being reinstalled)
 - coarse reproducibility (touching package.json results in a new XXX MB monolithic layer vs. XX MB package layer).  This becomes especially relevant pushing to a registry and then re-downloading the image.  It is notable that the XAR approach suffers this regardless.
 - Bazel deals better with `package-lock.json` than `package.json` (e.g. expecting reproducibility)

Fine-grained incrementality yields better caching, which ultimately should yield better deployment performance.  AIUI this is especially important in the serverless world, which is so sensitive to deploy performance.

---
Returning to the objective of maximizing commonality, I think the direction we want to head is:
1. support for `foo_install`ing a single dependency.
1. support for `foo_install`ing a `<pkg file>` (expose a filegroup of the above for each entry?).
1. support for `foo_image` (unlike the above prototype, this would be analogous to `par_binary`) which (IIUC) would package the app and its dependencies by walking `.runfiles` and intelligently constructing layers.  *(ideally this would be the only divergence from standard tooling)*

I need to dig into `par_binary` a bit and see if what it does to create the PAR archive can be applied to image construction as well.

**Comment by mattmoor** [comment]
My description of `3.` above may be too dynamic to actually express in Bazel, since it needs to know the actions when constructing the action graph.  However, perhaps a good approximation would be a layer per `deps` entry?

**Comment by mattmoor** [comment]
It looks like we might reasonably be able to partition the runfiles into individual layers per dependency that is enumerated in `foo_image`.  This would have the gotcha that:
```python
python_image(
   name = "foo",
   srcs = ["foo.py"],
   deps = [":my-one-library"],
)
```
would have a single dependency-layer, but:
```python
python_image(
   name = "foo",
   srcs = ["foo.py"],
   deps = [
       "@dep1//:target",
       "@dep2//:target",
       "@dep3//:target",
       ":my-one-library"
   ],
)
```
would have 4 dependency layers (and we could be clever about omitting redundancies from `:my-one-library` if they appear in the other libs).


FWIW, I've been poking around the Bazel graph with this little rule based on `par_binary` (I replaced one of the rules in `google/containerregistry` which has a few external deps):
```python
def _impl(ctx):
  """Explores the runfile tree."""

  # TODO(mattmoor): This depends on ordering of deps, which buildifier messes with,
  # instead we should sort each dep by the count of files ascending, which should ensure
  # supersets come last.
  seen = set()
  for dep in ctx.attr.deps:
    print("DEP: %s" % dep)
    roots = set()
    for input in list(dep.default_runfiles.files):
      roots += [input.root]
      if input.path in seen:
        continue
      seen += [input.path]
      print("file: %s" % input.short_path)

    for root in roots:
      print("root: %s" % root)


  return struct()

_explore = rule(
    attrs = {
        "src": attr.label(mandatory = True),
        "deps": attr.label_list(mandatory = False),
    },
    implementation = _impl,
)

def explore(name, deps, **kwargs):
  """Add a target that explores the Python dependency tree."""
  native.py_binary(name=name, deps=deps, **kwargs)
  _explore(name = name + ".explore", src=name, deps=deps)
```

A trick to explore for populating this list would be something like:
```python
load("@my_pip_install//:gen.bzl", "pip_deps")

# Or maybe python_image itself is imported from a generated .bzl file, which does this implicitly?
python_image(
   name = "foo",
   srcs = ["foo.py"],
   deps = pip_deps + [
       ":my-one-library"
   ],
)
```

**Comment by mattmoor** [comment]
In fact, if `pip_deps` were a dict, this might not be a bad way of enabling folks to use a `requirements.txt`, but still access deps using canonical names that don't map well to Bazel labels.  e.g. I know this is a problem in Node with package names containing `@` and `$`, but in this model you could use:
```python
load("@my_pip_install//:gen.bzl", "pip_deps")

py_library(
  name = "mylib",
  srcs = [...],
  deps = [
     ...
    pip_deps["@my-$pip-package"],
     ...
  ]
)
```

**Comment by duggelz** [comment]
Here's how I would like it to work, but I don't know how to get there:

- 0 or 1 `requirements.txt` file per Bazel package (~= per directory) that is the "canonical" source of versions.  Must have locked versions, so maybe `requirements.txt.lock`.
- A buildozer tool that reads `requirements.txt` files, and updates WORKSPACE and BUILD files appropriately

```
== WORKSPACE ==
pip_package('uwsgi', '2.0.13', sha256=...) # Munged to @uswgi__2_0_13
pip_package('uwsgi', '2.0.14', sha256=...)
pip_package('uwsgi', '2.0.15', sha256=...)
```
```
== foo/BUILD ==
pip_requirements(src='requirements.txt')
py_library(
  name = 'foo',
  deps = pip(['uwsgi']) # == version 2.0.15 because that's what foo/requirements.txt has
)
```

- Every Bazel target in a Bazel package with a `requirements.txt` can only depend on (a subset of) the Python packages+versions listed therein.
- Ergo, two Bazel targets in the same Bazel package can't depend on different versions of the same Python package.
- Something in `py_binary` checks that I don't depend on both '2.0.14' and '2.0.15'.
- I can duplicate the result of `bazel build foo` with an appropriate set of calls to `virtualenv`, `pip`, and `setup.py`

**Comment by mattmoor** [comment]
@duggelz I don't think we can read files at `BUILD` time and generate a variable set of actions, I think this must be done in `WORKSPACE` ahead of time. :(

Personally (and I don't think this mutually exclusive with anything you say), when a `requirements.txt` is imported as `@foo`, I'd like use to expand `BUILD` targets per dependency therein, reflecting some measure of the dependency structure, e.g. `@foo//uwsgi`.

That said, IDK that what you list is sufficient for correctness (ODR) because something in `//foo` might depend on something in `//bar`.  I wonder if we could make use of Bazel's constraint system somehow (without things becoming tediously verbose).

Perhaps we could use something like:
```python
load("@pip5//:generated.bzl", "pip")

py_binary(
   ...
   compatible_with = [pip.repo],
   deps = [
      pip.package["uwsgi"],
   ],
   ...
)
```

**Comment by mattmoor** [comment]
This is now handled by `rules_python`.

**Comment by edevil** [comment]
Could the Python 3 example be updated to use "rules_python" so that a few dependencies are installed via the usual requirements.txt file?
